apiVersion: batch/v1beta1
kind: CronJob
metadata: 
  name: cj-demo
spec: 
  schedule: "* * * * *"
  jobTemplate: 
    spec: 
      template: 
        spec: 
          containers: 
          - name: cj-demo
            image: busybox
            args: 
            - /bin/sh
            - -c
            - date; echo Hello
          restartPolicy: OnFailure
