apiVersion: v1
kind: Namespace
metadata: 
  name: kul
---
apiVersion: v1
kind: PersistentVolume
metadata: 
  name: kul-pv
  namespace: kul
spec: 
  capacity: 
    storage: 5Gi
  accessModes: 
  - ReadWriteMany
  nfs: 
    server: fs-8d6d070f.efs.us-east-1.amazonaws.com
    path: "/"
