apiVersion: v1
kind: Namespace
metadata: 
  name: kul
---
apiVersion: v1
kind: PersistentVolume
metadata: 
  name: kul-pv
  namespace: kul
spec: 
  capacity: 
    storage: 200Gi
  accessModes: 
  - ReadWriteMany
  nfs: 
    server: fs-8d6d070f.efs.us-east-1.amazonaws.com
    path: "/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: kul-pvc
  namespace: kul
spec: 
  accessModes: 
  - ReadWriteMany
  storageClassName: ""
  resources: 
    requests: 
      storage: 5Gi
---
apiVersion: v1
kind: ConfigMap
metadata: 
  name: kul-cm
  namespace: kul
data: 
  queue_manager_host: "somevalue"
  SMTP_SERVER: "smtp.thinknyx.com"
  SMTP_PORT: "25"
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: kul-deploy
  namespace: kul
spec: 
  replicas: 2
  selector: 
    matchLabels: 
      app: demo
  template: 
    metadata: 
      name: demo
      labels: 
        app: demo
    spec: 
      containers: 
      - name: busybox
        image: busybox
        command: 
          - sh
          - -c
          - 'while true; do date >> /mnt/index_kul.html; hostname >> /mnt/index_kul.html; sleep 5; done'
        imagePullPolicy: IfNotPresent

        env: 
        - name: db_host
          value: "mysql.thinknyx.com"
        - name: db_port
          value: "3306"

        - name: QM
          valueFrom:
            configMapKeyRef:
              name: kul-cm
              key: queue_manager_host

        envFrom:
        - configMapRef: 
            name: kul-cm

        volumeMounts: 
        - name: nfsdemo
          mountPath: /mnt
      volumes: 
      - name: nfsdemo
        persistentVolumeClaim:
          claimName: kul-pvc
