apiVersion: v1
kind: Namespace
metadata:
  name: kul

---

apiVersion: apps/v1
kind: Deployment

metadata: 
  name: d1-kul
  namespace: kul
  labels: 
    projectname: day3
    projecttype: bf
  annotations: 
    projectid: "1234"
    app_owner: "kul"
    support_team: "support@thinknyx.com"

spec: 
  template: 
    metadata: 
      labels: 
        app: day3
    spec: 
      containers: 
      - name: httpd
        #image: httpd
        #image: kulbhushanmayer/ericsson:bangalore-httpd-1.0
        image: thinknyx/vote:1.0
        #image: thinknyx/vote:2.0
     # nodeSelector: 
     #        kul: owner

  replicas: 15
  selector: 
    matchLabels: 
      app: day3
  strategy: 
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 5
---

apiVersion: v1
kind: Service
metadata: 
  name: d1-kul-svc
  namespace: kul
spec: 
  selector: 
    app: day3
  ports: 
  - port: 80
    nodePort: 30003
    protocol: TCP
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: d1-kul-svc-1
  namespace: kul
spec:
  selector:
    app: day3
  ports:
  - port: 80
    nodePort: 32767
    protocol: TCP
  type: NodePort


---

apiVersion: v1
kind: Service
metadata:
  name: d1-kul-svc-2
  namespace: kul
spec:
  selector:
    app: day3
  ports:
  - port: 80
#    nodePort: 32767
    protocol: TCP
  type: ClusterIP

