apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-container-demo
  labels:
    type: mcd
spec:
  replicas: 1
  selector: 
    matchLabels:
      type: mcd-demo
  template:
    metadata: 
      name: mcd-demo
      labels: 
        type: mcd-demo
    spec:       
      volumes:
      - name: html
        emptyDir: {}
      containers:
      - name: 1st
        image: nginx
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      - name: 2nd
        image: debian
        volumeMounts:
        - name: html
          mountPath: /html
        command: ["/bin/sh", "-c"]
        args:
          - while true; do
              date >> /html/index.html;
              sleep 1;
            done
